version: '3'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - yao
    depends_on:
      - mysql
  mysql:
    container_name: yao_mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3320:3306'
    volumes:
      - /var/www/yao/db:/var/lib/mysql
    networks:
      - yao
  phpmyadmin:
    container_name: yao_phpmyadmin
    image: phpmyadmin
    networks:
      - yao
    ports:
      - 8088:80
    environment:
      MYSQL_USERNAME: root
      PMA_HOST: mysql
networks:
  yao:
    driver: bridge